/* 195 ORP Scaling */

CREATE TABLE IF NOT EXISTS `team195_scouting`.`195OPR-Scaling` (
	`XXXXXXXXID` INT AUTO_INCREMENT NOT NULL,
	`XXXXXXXXX` VARCHAR(50) NULL,
	PRIMARY KEY(`XXXXXXXXX`))
Engine = InnoDB;