/* Current Event Analysis */

CREATE TABLE IF NOT EXISTS `team195_scouting`.`CurrentEventAnalysisGraphs` (
	`Team` VARCHAR(10) NULL,
	`EventID` INT NULL,
	`AutonomousMean` INT NULL,
	`AutonomousMedian` INT NULL,
	`AutonomousFormat` INT NULL,
	`TotalBallsMean` INT NULL,
	`TotalBallsMedian` INT NULL,
	`TotalBallsFormat` INT NULL,
	`TotalScoreMean` INT NULL,
	`TotalScoreMedian` INT NULL,
	`TotalScoreFormat` INT NULL,
	`ClimbMean` INT NULL,
	`ClimbMedian` INT NULL,
	`ClimbFormat` INT NULL,
	`TeleHighBallsMean` INT NULL,
	`TeleHighBallsMedian` INT NULL,
	`TeleHighBallsFormat` INT NULL,
	`TeleLowBallsMean` INT NULL,
	`TeleLowBallsMedian` INT NULL,
	`TeleLowBallsFormat` INT NULL,
	`TeleTotalBallsMean` INT NULL,
	`TeleTotalBallsMedian` INT NULL,
	`TeleTotalBallsFormat` INT NULL,
	`AutonomousScoreMean` INT NULL,
	`AutonomousScoreMedian` INT NULL,
	`AutonomousScoreFormat` INT NULL,
	`TeleBallScoreMean` INT NULL,
	`TeleBallScoreMedian` INT NULL,
	`TeleBallScoreFormat` INT NULL,
	`Summary` INT NULL,
	`SummaryFormat` INT NULL)
Engine = InnoDB;
